# Generated by Django 4.2.7 on 2026-02-01 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000), django.core.validators.MaxValueValidator(2100)])),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('dimensions', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('condition', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='records/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.collection')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collection'], name='api_record_collect_241dcc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner'], name='api_collect_owner_i_5dbf34_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_closed'], name='api_collect_is_clos_87b490_idx'),
        ),
    ]
