# Generated by Django 4.2.7 on 2026-04-11 07:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_system_identity_and_import_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='collection',
            new_name='api_collect_is_list_8f44be_idx',
            old_name='api_collect_is_list_7a8b9c_idx',
        ),
        migrations.AlterField(
            model_name='collection',
            name='stable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
