# Generated by Django 4.2.7 on 2026-04-13 17:22

import mimetypes
import os
import uuid

from django.core.files.base import ContentFile
from django.db import migrations, models
import django.db.models.deletion


def migrate_representative_to_record_images(apps, schema_editor):
    """
    Move legacy Record.representative_image files into RecordImage rows
    (role=thumbnail, context=portfolio, is_primary=True), then clear the legacy field.

    API continues to expose representative_image as an absolute URL by resolving
    from the first matching RecordImage when the legacy field is empty.
    """
    Record = apps.get_model("api", "Record")
    RecordImage = apps.get_model("api", "RecordImage")
    # Import analysis helper (stable module path for migrations).
    from api.record_image_ingest import analyze_image_bytes

    for rec in Record.objects.iterator():
        field = rec.representative_image
        if not field:
            continue
        try:
            with field.open("rb") as fh:
                data = fh.read()
        except OSError:
            continue
        name = getattr(field, "name", "") or ""
        basename = os.path.basename(name) or "legacy.jpg"
        ctype = mimetypes.guess_type(basename)[0]
        try:
            info = analyze_image_bytes(
                data,
                original_name=basename,
                reported_content_type=ctype,
            )
        except ValueError:
            continue
        unique = f"migrated_{rec.pk}_{uuid.uuid4().hex[:12]}_{basename}"
        cf = ContentFile(data, name=unique)
        ri = RecordImage(
            record_id=rec.pk,
            role="thumbnail",
            context="portfolio",
            byte_size=info["byte_size"],
            width=info["width"],
            height=info["height"],
            magick_format=info.get("magick_format"),
            mime_type=info["mime_type"],
            checksum_sha256=info["checksum_sha256"],
            sort_order=0,
            is_primary=True,
            status="draft",
            labels={},
        )
        ri.image.save(unique, cf, save=True)
        field.delete(save=False)
        rec.representative_image = None
        rec.save(update_fields=["representative_image"])


def noop_reverse_record_images(apps, schema_editor):
    """Cannot restore legacy files from RecordImage rows."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_collection_owning_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='records/')),
                ('role', models.CharField(choices=[('thumbnail', 'thumbnail'), ('preview', 'preview'), ('preservation_master', 'preservation_master'), ('access_derivative', 'access_derivative'), ('derivative', 'derivative'), ('print', 'print'), ('detail', 'detail'), ('document_scan', 'document_scan')], max_length=32)),
                ('context', models.CharField(choices=[('portfolio', 'portfolio'), ('exhibit', 'exhibit'), ('archive', 'archive'), ('documentation', 'documentation'), ('condition', 'condition'), ('publication', 'publication'), ('digitalization', 'digitalization')], max_length=32)),
                ('byte_size', models.PositiveIntegerField()),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('magick_format', models.CharField(blank=True, max_length=32, null=True)),
                ('mime_type', models.CharField(max_length=128)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('approved', 'approved'), ('suppressed', 'suppressed')], default='draft', max_length=16)),
                ('labels', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derived_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='api.recordimage')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.record')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['record', 'sort_order'], name='api_recordi_record__c8b6b1_idx'), models.Index(fields=['record', 'role', 'context'], name='api_recordi_record__c8bbee_idx')],
            },
        ),
        migrations.RunPython(
            migrate_representative_to_record_images,
            noop_reverse_record_images,
        ),
    ]
