# Generated by Django 4.2.7 on 2026-04-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recordimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordimage',
            name='context',
            field=models.CharField(choices=[('portfolio', 'portfolio'), ('exhibit', 'exhibit'), ('archive', 'archive'), ('documentation', 'documentation'), ('condition', 'condition'), ('object_condition_survey', 'object_condition_survey'), ('publication', 'publication'), ('digitalization', 'digitalization')], max_length=32),
        ),
    ]
