[supervisord]
nodaemon=true
loglevel=info

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=10
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:gunicorn]
directory=/app
command=gunicorn ekho_backend.wsgi:application --bind 127.0.0.1:8001 --workers 2 --threads 2 --timeout 120 --access-logfile - --error-logfile -
priority=20
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
environment=DJANGO_SETTINGS_MODULE="ekho_backend.settings_deployment"
